spring:
  # Spring Data JPA configuration
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  # Database
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: asesoftware
    password: admin123

  h2:
    console:
      enabled: true
      path: /h2